### ISSUE TITLE
unhandled opcode

### ISSUE THREAD

**Issue by inf3rno** [jlaine/node-jpickle#7]
I'd like to convert data from here: https://github.com/lmmentel/mendeleevapp/tree/master/app/data into JSON. I checked the code, it does `new Buffer(param, "binary")` with the param, which is deprecated if the param is a bufffer. I tried to load the file several ways and got different error messages each time:

```
jpickle.loads(fs.readFileSync("./neutral_0.3.2.pkl"));
Unhandled opcode '128'

jpickle.loads(fs.readFileSync("./neutral_0.3.2.pkl", "utf8"));
Unhandled opcode '�'

jpickle.loads(fs.readFileSync("./neutral_0.3.2.pkl", "binary"));
Unhandled pickle protocol version: 4
```

Any idea why it cannot parse the file?

**Comment by jlaine** [comment]
The last message is the correct one: `Unhandled pickle protocol version: 4`, jpickle doesn't currently support pickle protocol version 4 (supported by Python >= 3.4). If you try to open the file with an older Python you also get: `ValueError: unsupported pickle protocol: 4`

**Comment by inf3rno** [comment]
@jlaine Any idea how to convert it to JSON without any Python knowledge?

**Comment by inf3rno** [comment]
I tried with python too:
```py
import pickle
import json
with open("neutral_0.3.2.pkl") as pickle_file:
    data = pickle.load(pickle_file)
with open("data_file.json", "w") as write_file:
    json.dump(data, write_file)
```
But it cannot unpickle it.
```
with open("neutral_0.3.2.pkl") as pickle_file:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 46: chara cter maps to

with open("neutral_0.3.2.pkl", encoding="utf-8") as pickle_file:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid  start byte

with open("neutral_0.3.2.pkl", encoding="Latin-1") as pickle_file:
TypeError: a bytes-like object is required, not 'str'
```

I could try to covert the last one into a buffer, but I guess it would have worked with utf-8 too, because afaik. Latin-1 is a subset of that. But maybe I am wrong. I have no idea what encoding that file uses. I checked the code from where I downloaded it, but it does not contain any pickle.load. I have no idea how it loads that file.

**Comment by jlaine** [comment]
Background: pickle files can contain both primitive types (integers, floats, strings..) and objects from arbitrary third party packages.

The specific pickle file you provided references both `pandas` and `sqlalchemy`, so reading it from Javascript is going to fail even if `node-jpickle` supported protocol 4.

After installing the `pandas` and `sqlalchemy` packages I can read your file using:

```python
import pandas

with open('neutral_0.3.2.pkl', 'rb') as pickle_file:
    df = pandas.read_pickle(pickle_file)

with open('neutral_0.3.2.pkl', 'w') as json_file:
    json_file.write(df.to_json())
```

How you decide
